# -*- coding: utf-8 -*-
"""Helenhuqua

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cJ5jsc2I0Dj-PQGPYNdBDDKZ_0CKa00S
"""

!pip install streamlit
import streamlit as st
import matplotlib.pyplot as plt
import pandas as pd
st.title('Simple Bar Chart Example')
data = {'Category': ['A', 'B', 'C', 'D'],
        'Values': [3, 7, 2, 5]}

df = pd.DataFrame(data)
st.write('Data for the Bar Chart:')
st.write(df)
fig, ax = plt.subplots()
ax.bar(df['Category'], df['Values'])
ax.set_xlabel('Category')
ax.set_ylabel('Values')
ax.set_title('Bar Chart Example')
st.pyplot(fig)